### ISSUE TITLE
A small typo

### ISSUE THREAD

**Issue by cansirin** [ramazansancar/weatherApi#1]
Hello @ramazansancar,

I am coming from the link in the [Kampus discord](https://discord.gg/kampus) :) While I was reading your code, I found this small typo. Then I started seeing everywhere :) I believe all `'params:'` fields should be replaced with `"params":`.

https://github.com/ramazansancar/weatherApi/blob/master/controllers/weather/index.js#L50

I like writing object fields without quotation marks, maybe you can find it useful too!

**Comment by ramazansancar** [comment]
Hello @cansirin,
Thanks for your feedback. I made a few changes to optimize the code. Hopefully something better will come out this time.
